### ISSUE TITLE
More metrics

### ISSUE THREAD

**Issue by mickeypash** [sirupsen/napkin-math#13]
Maybe it's worth adding these?
- A packet round trip within a datacenter
- Pinging an external DNS server

**Comment by sirupsen** [comment]
Hey, sorry for the late reply @mickeypash -- thanks for opening the issue.

(1) Packet round trip is there as `Network within same region`. I've cleaned that up a bit since you posted. Is this clear?

(2) Hm interesting, specifically DNS strikes me as too niche to include. A broader category would be to list latency percentiles (P50/P90/P99) of latency for IPs that have a significant number of points of presence. Such as big DNS providers like Cloudflare/Google/Dyn/Route 53/Akamai. This would then not just apply to DNS, but also to things like serving traffic out of edge networks.

**Comment by mickeypash** [comment]
Actually I was doing a TripleByte multiple choice quiz when applying for a startup.
This immediately struck me as something of interest here.
```
Which of the following data operations would be most likely to run sub-millisecond?

- A disk seek
- Reading 10MB sequentially from a SSD
- A packet round trip within a datacenter
- Pinging an external DNS server

```

**Comment by sirupsen** [comment]
Funny, what did you answer?

Disk seek: Just put this in the reference (8f4cb97), they don't specify HDD/SSD, but `seek` usually refers to HDD ~10ms.

10MB sequentially: 200 us / 1 MiB = 2 ms

Packet round trip within a datacenter: Usually 250-500 us

Pinging an external DNS server: 20-40ms

It's kind of close between 10 MB sequentially and a round-trip, which was the correct answer? I find many people overestimate intra-dc packet roundtrips because the server is usually 'slow.'

**Comment by mickeypash** [comment]
I can't remember now but I might have gone for the disk seek? I certainly did't know enough and overestimated the round-trip and DNS ping by an order of magnitude.
Btw I also stumbled onto the wiki article you've references in your commit and it has states the following:
> The fastest high-end server drives today have a seek time around 4 ms
However I did some quick checks on WesterDigital's site and I couldn't find such impressive numbers.

**Comment by sirupsen** [comment]
@mickeypash ya, I saw the 4ms. When prefaced with "high-end server drives", I didn't quite believe it. 10ms is nice and easy to remember and will likely work well as an estimate, while the avg. might be slightly higher, in reality you'll hit various caches and likely get a better average performance.

Would need to run some tests on an HDD in the future.
