### ISSUE TITLE
Data center level benchmarks?

### ISSUE THREAD

**Issue by chadbrewbaker** [sirupsen/napkin-math#18]
There is an uncanny valley missing at a cloud vendor data center level.

I was thinking of contributing some benchmarks via shell. While I was at it also try to get some market prices to integrate cost.

Is this a good model for Azure/GCP too or am I missing a common data center abstraction?

- [ ] In data center DNS.
- [ ] Vendor permission authentication (AWS IAM equivalent)
- [ ] Latency/bandwith/concurrency of blob store (AWS S3 equivalent)
- [ ] Latency with vendor control plane API (AWS CLI equivalent)
- [ ] Latency/bandwidth/concurrency of block storage (AWS EBS equivalent)
- [ ] Latency of vendor stock linux container worker (AWS Lambda equivalent)
- [ ] Latency/bandwidth/concurrency of message ingress (AWS Kinesis equivalent)

**Comment by sirupsen** [comment]
Hey, thanks for opening this discussion :)

> Is this a good model for Azure/GCP too or am I missing a common data center abstraction?

Currently try to not distinguish too much between cloud and metal, since generally it's within ~1 order of magnitude, if that's what you mean.

I am in general a little hesitant on specific services, as I think you should be able to easily derive them from other numbers. If it's complicated and common enough, then it may be worth it.

> data center DNS

Isn't this just basic network latency within a zone, i.e. ~0.5ms? I don't think we need a specific number.

>  Vendor permission authentication (AWS IAM equivalent)

Is this called at runtime enough to matter?

>  Latency/bandwith/concurrency of blob store (AWS S3 equivalent)

Is this too complicated to derive from existing metrics, or does it not line up with those metrics?

>  Latency with vendor control plane API (AWS CLI equivalent)

Why isn't this just network latency in the zone? Is there any heavy processing here? Is this really common enough?

>  Latency/bandwidth/concurrency of block storage (AWS EBS equivalent)

This one I'm quite interested in. It's been on my list for a while to evaluate network-based storage, as I could see this being different than SSD-semantics.

>  Latency of vendor stock linux container worker (AWS Lambda equivalent)

You mean time to spin these serverless runtimes up? Or added latency to e.g. system calls etc.? What do you mean here?

>  Latency/bandwidth/concurrency of message ingress (AWS Kinesis equivalent)

Similar to others, I think this should likely be derived from existing numbers
