### ISSUE TITLE
Limit memory allocations by size instead of time

### ISSUE THREAD

**Issue by DavidVentura** [sirupsen/napkin-math#2]
Hey

On my machine, I can write to memory at ~3GB/s, but I don't have 5 seconds worth of memory available to allocate. By changing the benchmark duration to 3.5s the writes finish succesfully (otherwise I get an allocation error).

It'd be nice to be able to limit the memory usage by available memory instead of by time.

```
[Write Seq Vec<usize>] Iterations in 2004 miliseconds, no overhead: 899,250,576
[Write Seq Vec<usize>] Iterations / second: 448,727,832
[Write Seq Vec<usize>] Bytes handled per iteration: 8 bytes
[Write Seq Vec<usize>] Total bytes processed: 6.700 GiB
[Write Seq Vec<usize>] Throughput: 3.343 GiB/s
[Write Seq Vec<usize>] Avg single iteration: 2.230 ns
[Write Seq Vec<usize>] Avg single iteration cycles: 8.51
[Write Seq Vec<usize>] Time to process 1 MiB: 292 μs
[Write Seq Vec<usize>] Time to process 1 GiB: 299 ms
[Write Seq Vec<usize>] Time to process 1 TiB: 5.10 min
```

**Comment by sirupsen** [comment]
Yes, agree. There's also some benchmarks that run for little time because it only traverses the memory once. Likely the best way to fix this is that we always run two benchmarks for each run. One to get a rough sense of performance, and one to do the real thing with less comparisons based on the first. We could use that first benchmark to figure out numbers like this for the 2nd run..? WDYT?

**Comment by sirupsen** [comment]
What machine is that? That's pretty good performance.

**Comment by sirupsen** [comment]
Should work now.
